### ISSUE TITLE
Right way to handle errors.

### ISSUE THREAD

**Issue by humb1t** [ntex-rs/ntex-grpc#11]
Hello, thanks a lot for this interesting project for gRPC support in Rust ecosystem.
I'm working on a replacing of tonic with ntex-grpc. One thing that I'm struggling with at the moment is error handling.
What is the ntex-grpc way to handle errors in server?
```
    #[method(VerifyCredentials)]
    async fn verify_credentials(
        &self,
        VerifyCredentialsRequest { token }: VerifyCredentialsRequest,
    ) -> Result<VerifyCredentialsResponse> {
```

My idea was to use `Result` in method definition, but maybe idea in ntex-grpc is to write possible error structures in proto file and use oneof with success/fail structures for response types?

**Comment by fafhrd91** [comment]
at the moment error handling in server side is not very detailed, you have to return proto response.

if you really want to use ntex-grpc, you have to be prepared to dig in internals. i didnt work on server side api much, it is need more work in term of usability

**Comment by humb1t** [comment]
@fafhrd91 thanks a lot. I can contribute and interested in it. Can you please help with defining your ideas or thoughts on it and I will try to implement them.

**Comment by fafhrd91** [comment]
quick idea, is to use `Responder` style trait, similar to actix-web or ntex.

so by method call would be something like:

```rust
async fn method(&self, req: proto::Request) -> impl Responder<proto::Response>;
```

then it would be possible to define `Responder` like:

```rust
impl<T, E> Responder<Result<T, E>> for proto::Response 
where
   T: Into<proto::Response>
   E: Into<proto::Response>
{
}
```

also `Into` could be replaced with `TryInto`, so failed conversion could be treated as grpc level error

**Comment by fafhrd91** [comment]
this is just an idea, feel free to design something more interesting

**Comment by humb1t** [comment]
I think it's a good idea. I will start working on it late March, early April.

**Comment by fafhrd91** [comment]
added simple response error handling Result<Method::Output, impl Into<Method::Output>>
