### ISSUE TITLE
codegen works incorrectly with multiple proto files

### ISSUE THREAD

**Issue by humb1t** [ntex-rs/ntex-grpc#17]
When several proto files are presented, and you try to generate to one of them which imports other protos, generate creates several identical `#[allow...]` statements + conflicting _priv_impl modules.

--Example of repo that uses ntex-grpc, but cleans up manually after generation: https://gitlab.com/oss47/tari_rgrpc#--

Will provide an example later, the one I wanted to use need streams support which is not currently available in ntex-grpc

**Comment by fafhrd91** [comment]
I see. thanks for report

**Comment by fafhrd91** [comment]
ntex-grpc-codegen 0.2.12 is released with fix

**Comment by humb1t** [comment]
wow, thanks @fafhrd91 💜
