### ISSUE TITLE
support f32, f64

### ISSUE THREAD

**Issue by MindMayhem** [ntex-rs/ntex-grpc#2]
Hi, there's problem with derive Eq, we can't use any floats types from our protobuf files because they are doesn't support Eq derive

possible solution is use

`#[derive(Clone, PartialEq, Debug)]`

instead of

`#[derive(Clone, PartialEq, Eq, Debug)]`

like it done in prost

**Comment by fafhrd91** [comment]
fixed in main

**Comment by MindMayhem** [comment]
not fixed, https://github.com/ntex-rs/ntex-grpc/issues/3
