### ISSUE TITLE
support timestamp and other google types

### ISSUE THREAD

**Issue by MindMayhem** [ntex-rs/ntex-grpc#3]
hi, currently we are unable to use prost-types due to other grpc implementation from ntex

i think, this's really important type (and other types too) and they're should be adapted to use with ntex-grpc

**Comment by fafhrd91** [comment]
added Timestamp and Duration for now

**Comment by fafhrd91** [comment]
timestamp is reachable, it is hidden. i will expose it in next version. but use should work, you can also convert SystemTime to Timestamp with TryFrom trait


usa _grpc::google_types::Timestamp;
