### ISSUE TITLE
f32 boundary issue

### ISSUE THREAD

**Issue by kitsuniru** [ntex-rs/ntex-grpc#4]
`ntex_grpc::NativeType::deserialize` and `ntex_grpc::NativeType::serialized_len`

```
the trait bound `f32: ntex_grpc::Message` is not satisfied
the following other types implement trait `ntex_grpc::Message`: 
```

on generated protobufs which contains f32

**Comment by MindMayhem** [comment]
seems like f32 support not fully completed, bcs we don't have `impl NativeType for f32` encoder function

**Comment by fafhrd91** [comment]
fixed
